config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  post '/login', to: 'landing#login', as: 'landing_post'
  get '/home', to: 'home#index', as: 'home'
  get '/home/customers', to: 'customers#index', as: 'customers'
  get '/home/customers/:id', to: 'customers#show', as: 'customer'
  get '/invoices', to: 'invoices#index', as: 'invoices'
  get '/invoices/begin', to: 'invoices#begin', as: 'begin_invoice'
  get '/invoices/new', to: 'invoice#new', as: 'new_invoice'
  get '/invoices/search', to: 'invoices#search', as: 'search_invoices'
  get '/invoices/:id', to: 'invoices#show', as: 'invoice'
  get '/invoices/:id/edit', to: 'invoices#edit', as: 'edit_invoice'
  post '/invoices', to: 'invoices#new', as: 'post_new_invoice'
  post '/invoices/create', to: 'invoices#create', as: 'create_invoice'
  get '/products', to: 'products#index', as: 'products'
  get '/products/search', to: 'products#search', as: 'search_products'
  get '/products/inventory', to: 'products#inv', as: 'user_inv_products'
  get '/products/:id', to: 'products#show', as: 'product'

  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  belongs_to :user
  has_many :line_items
  has_many :products, :through => :line_items
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices=Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def begin
    @customers=Customer.all.pluck('last_name')
    @users=User.all.pluck('username')
  end

  def new
    @invoice=Invoice.new(:customer_id=>Customer.find_by_last_name(params[:customer]).id, :user_id=>User.find_by_username(params[:user]).id)
  end

  def search
    @invoices=Invoice.all
    render 'index'
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice=Invoice.new(:user_id=>params[:user_id],:customer_id=>params[:customer_id],:job_date=>params[:job_date],:items=>params[:items])

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully saved.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:id, :customer_name, :customer_address, :items, :job_date)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<h1>Edit Page</h1>

<div class="customerBlock">
  <table>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
    </tr>
    <tr>
      <td><%= "#{invoice.customer.first_name} #{invoice.customer.last_name}" %></td>
      <td><%= invoice.customer.phone %></td>
      <td><%= invoice.customer.email %></td>
    </tr>
    <tr>
      <th>Address</th>
    </tr>
    <tr>
      <td><%= invoice.customer.address %></td>
    </tr>
    <tr>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
    </tr>
    <tr>
      <td><%= invoice.customer.city %></td>
    <td><%= invoice.customer.state %></td>
      <td><%= invoice.customer.zip %></td>
    </tr>
  </table>
</div>

  <%= form_tag create_invoice_path do %>
    <div class="miscBlock">
      <table>
        <tr>
          <th>User</th>
          <th>Date</th>
        </tr>
        <tr>
          <td><%= "#{invoice.user.first_name} #{invoice.user.last_name}" %></td>
          <td><%= date_field_tag :job_date, invoice.job_date %></td>
        </tr>
      </table>
    </div>
    
    <%= hidden_field_tag 'customer_id', invoice.customer_id %>
    <%= hidden_field_tag 'user_id', invoice.user_id %>

    <div class="itemsBlock">
      <%= label_tag :items %>
      <%= text_area_tag :items, invoice.items %>
      <%= submit_tag 'Submit' %>
    </div>
  <% end %>

app/views/invoices/begin.html.erb
<h1>
  CHS Job
</h1>

<div class="block">
  <%= form_tag post_new_invoice_path do %>
    <%= select_tag 'customer', options_for_select(@customers), prompt: 'Select Customer' %>
    <%= select_tag 'user', options_for_select(@users), prompt: 'Select User' %>
    <%= submit_tag 'Create Invoice' %>
  <% end %>
</div>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', :invoice => @invoice %>

<%= link_to 'Show', invoice_path(@invoice) %> 
<%= link_to 'Back', invoices_path %> 

app/views/invoices/index.html.erb
<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Invoice ID</th>
      <th>User</th>
      <th>Customer</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.id %></td>
        <td><%= invoice.user.username %></td>
        <td><%= "#{invoice.customer.first_name} #{invoice.customer.last_name}" %></td>
        <td><%= invoice.job_date %></td>
        <td><%= link_to 'Show', invoice_path(invoice) %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', :invoice => @invoice %>

app/views/invoices/search.html.erb
<h1>Search Page</h1>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice Show</h1>

<div class="customerBlock">
  <table>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
    </tr>
    <tr>
      <td><%= "#{@invoice.customer.first_name} #{@invoice.customer.last_name}" %></td>
      <td><%= @invoice.customer.phone %></td>
      <td><%= @invoice.customer.email %></td>
    </tr>
    <tr>
      <th>Address</th>
    </tr>
    <tr>
      <td><%= @invoice.customer.address %></td>
    </tr>
    <tr>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
    </tr>
    <tr>
      <td><%= @invoice.customer.city %></td>
    <td><%= @invoice.customer.state %></td>
      <td><%= @invoice.customer.zip %></td>
    </tr>
</div>

  <div class="miscBlock">
      <tr>
        <th>User</th>
        <th>Date</th>
      </tr>
      <tr>
        <td><%= "#{@invoice.user.first_name} #{@invoice.user.last_name}" %></td>
        <td><%= @invoice.job_date %></td>
      </tr>
  </div>

  <div class="itemsBlock">
    <tr>
      <th>Description</th>
      <th colspan='3'></th>
    </tr>
    <tr>
      <td><%= @invoice.items %></td>
    </tr>
  </div>
  </table>

<%= link_to 'Edit', edit_invoice_path(@invoice) %>
<%= link_to 'Back', invoices_path %>

app/views/invoices/test.html.erb
<h1>
  Ok, this is the test
</h1>

<table>
  <tr>
    <th>
      Left
    </th>
    <th>
     Right
    </th>
    <th>
      Center
    </th>
  </tr>

  <tr>
    <td class="left">
     This stuff should be in the left column
    </td>
    <td class="center">
    This stuff should be centered muthafucka
    </td>
    <td class="right">
     This muthafuckin shit should be on the right muthafuckin side of the
      muthafuckin page
   </td>
  </tr>
</table>