config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  post '/login', to: 'landing#login', as: 'landing_post'
  get '/home', to: 'home#index', as: 'home'
  get '/home/customers', to: 'customers#index', as: 'customers'
  get '/home/customers/:id', to: 'customers#show', as: 'customer'
  get '/invoices', to: 'invoices#index', as: 'invoices'
  get '/invoices/begin', to: 'invoices#begin', as: 'begin_invoice'
  get '/invoices/new', to: 'invoice#new', as: 'new_invoice'
  get '/invoices/search', to: 'invoices#search', as: 'search_invoices'
  get '/invoices/:id', to: 'invoices#show', as: 'invoice'
  get '/invoices/:id/edit', to: 'invoices#edit', as: 'edit_invoice'
  post '/invoices', to: 'invoices#new', as: 'post_new_invoice'
  post '/invoices/create', to: 'invoices#create', as: 'create_invoice'
  get '/products', to: 'products#index', as: 'products'
  get '/products/search', to: 'products#search', as: 'search_products'
  get '/products/inventory', to: 'products#inv', as: 'user_inv_products'
  get '/products/:id', to: 'products#show', as: 'product'

  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :invoices, :through => :line_items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :product_code %>
  </div>

  <div class="field">
    <%= form.label : %>
    <%= form.text_field :, id: :product_ %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag(product.image_url) %></td>
        <td><%= product.code %></td>
        <td><%= product.description %></td>
        <td></td>
        <td><%= link_to 'Show', product_path(product) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Product</h1>

<div class="productBlock">
  <table>
    <tr>
      <th>Code</th>
      <th colspan="2">Description</th>
    </tr>
    <tr>
      <td><%= @product.code %></td>
      <td colspan="2"><%= @product.description %></td>
    </tr>
    <tr>
      <td colspan="3"><%= image_tag(@product.image_url) %></td>
    </tr>
    <tr>
      <th>Vender A Cost</th>
      <th>Vender B Cost</th>
      <th>Vender C Cost</th>
    </tr>
    <tr>
      <td><%= @product.cost_vender_a %></td>
      <td><%= @product.cost_vender_b %></td>
      <td><%= @product.cost_vender_c %></td>
    </tr>
    <tr>
      <th colspan="3">CHS Price</th>
    </tr>
    <tr>
      <td clospan="3"><%= @product.price %></td>
    </tr>
  </table>
</div>
      
<%= link_to 'Back', products_path %>