config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  post '/login', to: 'landing#login', as: 'landing_post'
  get '/home', to: 'home#index', as: 'home'
  get '/home/customers', to: 'customers#index', as: 'customers'
  get '/home/customers/:id', to: 'customers#show', as: 'customer'
  get '/invoices', to: 'invoices#index', as: 'invoices'
  get '/invoices/begin', to: 'invoices#begin', as: 'begin_invoice'
  get '/invoices/new', to: 'invoice#new', as: 'new_invoice'
  get '/invoices/search', to: 'invoices#search', as: 'search_invoices'
  get '/invoices/:id', to: 'invoices#show', as: 'invoice'
  get '/invoices/:id/edit', to: 'invoices#edit', as: 'edit_invoice'
  post '/invoices', to: 'invoices#new', as: 'post_new_invoice'
  post '/invoices/create', to: 'invoices#create', as: 'create_invoice'
  get '/products', to: 'products#index', as: 'products'
  get '/products/search', to: 'products#search', as: 'search_products'
  get '/products/inventory', to: 'products#inv', as: 'user_inv_products'
  get '/products/:id', to: 'products#show', as: 'product'

  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_side_menu_customers.html.erb
<div class="side_menu_text">
  <ul>
    <li><%= link_to 'Invoices', search_invoices_path %>
    <li><%= link_to 'New Job', begin_invoice_path %>
    <li><%= link_to 'Customers', customers_path %>
  </ul>
</div>

app/views/layouts/_side_menu_home.html.erb
<div class="side_menu_text">
  <ul>
    <li><%= link_to 'News', home_path %>
    <li><%= link_to 'Time Log', home_path%>
    <li><%= link_to 'Settings', home_path %>
  </ul>
</div>

app/views/layouts/_side_menu_invoices.html.erb
<div class="side_menu_text">
  <ul>
    <li><%= link_to 'Invoices', search_invoices_path %>
    <li><%= link_to 'New Job', begin_invoice_path %>
    <li><%= link_to 'Customers', customers_path %>
  </ul>
</div>

app/views/layouts/_side_menu_products.html.erb
<div class="side_menu_text">
  <ul>
    <li><%= link_to 'Search', search_products_path %>
    <li><%= link_to 'Catalog', products_path %>
    <li><%= link_to 'Inventory', user_inv_products_path %>
  </ul>
</div>

app/views/layouts/_top_menu.html.erb
<div class="top_menu_text">
  <%= link_to 'Home', home_path %>
  <%= link_to 'Job', invoices_path %>
  <%= link_to 'Products', products_path %>
  <div class="signout">
    <%= link_to 'Sign Out', '/' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CHS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main_body">

    <header>
      <%= render 'layouts/top_menu' if controller_name!='landing' %>
    </header>

    <aside>
      <%= render "layouts/side_menu_#{controller_name}" if controller_name!='landing' %>
    </aside>

    <div class="workspace">
      <%= yield %>
    </div>

    <footer>
    </footer>
  </body>

  </html>